Feature: Transforms
aai-institute/continuity pull request #43
Opened 2024-02-15 12:43 UTC by JakobEliasWagner

## Description

Transforming tensors in the setting of neural operators can have many reasons. Transformations can improve model performance, enhance generalization, enable varied input size inputs, facilitate feature extraction, reduce overfitting, improve computational efficiency, or much more. 
Currently these transformations need to be applied manually and are dependent on the implementation of the end user. The result is difficulty in implementing correct transformations and especially chained transformations are difficult to apply. This issue aims to introduce a base transformation class for all tensors.

### Which issue does this PR tackle?

  - Transformations of tensors are currently not implemented.
  - Partly addresses #38

### How does it solve the problem?

  - Introduces a transform base class.
  - Introduces a Compose class which executes multiple transformations sequentially.

### How are the changes tested?

- Added tests for backward and forward pass of `Transform` with dummy classes.
- Added tests for backward and forward pass of `Compose` with dummy classes. The order of the applied transformations proof that the order in which they are called in backward and forward is correct.

## Checklist for Contributors

- [x] Scope: This PR tackles exactly one problem.
- [x] Conventions: The branch follows the `feature/title-slug` convention.
- [x] Conventions: The PR title follows the `Bugfix: Title` convention.
- [x] Coding style: The code passes all pre-commit hooks.
- [x] Documentation: All changes are well-documented.
- [x] Tests: New features are tested and all tests pass successfully.
- [x] Changelog: Updated CHANGELOG.md for new features or breaking changes.
- [x] Review: A suitable reviewer has been assigned.

## Checklist for Reviewers:

- [ ] The PR solves the issue it claims to solve and only this one.
- [ ] Changes are tested sufficiently and all tests pass.
- [ ] Documentation is complete and well-written.
- [ ] Changelog has been updated, if necessary.

2024-02-21 10:45 UTC, samuelburbulla requested changes

2024-02-21 10:45 UTC, JakobEliasWagner commented on src/continuity/transforms/transform.py
> +    def backward(self, tensor: torch.Tensor) -> torch.Tensor:
is `undo` a good other name?

2024-02-21 12:12 UTC, JakobEliasWagner commented on tests/transforms/test_transform.py
> +    assert torch.allclose(abs_transform.backward(random_tensor), random_tensor)
This would require to change the testing parameters set in `pyproject.toml`. Warnings are ignored by default -> changing this to facilitate testing for wranings.

2024-02-21 12:13 UTC, JakobEliasWagner commented on tests/transforms/fixtures.py
> +
A warning has been introduced here in [8166a17](https://github.com/aai-institute/continuity/pull/43/commits/8166a17d8b66b1c79d2231f0158cc3d0e589b549).

2024-02-21 12:13 UTC, JakobEliasWagner commented on src/continuity/transforms/transform.py
> +    def backward(self, tensor: torch.Tensor) -> torch.Tensor:
Renamed it to undo in [8166a17](https://github.com/aai-institute/continuity/pull/43/commits/8166a17d8b66b1c79d2231f0158cc3d0e589b549).

2024-02-21 12:28 UTC, JakobEliasWagner commented on tests/transforms/test_transform.py
> +    assert torch.allclose(abs_transform.backward(random_tensor), random_tensor)
Changed default to not filter UserWarnings in [4c5eb61](https://github.com/aai-institute/continuity/pull/43/commits/4c5eb61f22a34e45a38b8a9393a1a3554d4fce25). Added a test to check for a warning in [589eb1b](https://github.com/aai-institute/continuity/pull/43/commits/589eb1b7e5348eddbd80b6d2fcb491f952721188).

2024-02-21 12:37 UTC, JakobEliasWagner reviewed
Adapted to requested changes. Need some further clarification on whether it is okay to remove the UserWarning Filter.

2024-02-22 08:37 UTC, samuelburbulla approved these changes

2024-02-22 08:43 UTC, merged