Feature/z normalization
aai-institute/continuity pull request #51
Opened 2024-02-22 09:51 UTC by JakobEliasWagner

# Bugfix/Feature/Cleanup: PR Name

## Description

This pull request introduces a new feature for data preprocessing: Z-Normalization. Z-Normalization, also known as standardization, is a technique used to scale data so that it has a mean of 0 and a standard deviation of 1. This process is essential in many machine learning algorithms as it ensures that each feature contributes equally to the analysis, improving the performance and stability of the models.

### Which issue does this PR tackle?

  - Addresses the need for a standardized data preprocessing step in our machine learning pipeline. The lack of a z-normalization feature has been a significant gap in our data preprocessing capabilities, leading to suboptimal performance in models sensitive to the scale of data.

### How does it solve the problem?

  - Implements Z-normalization.
  - Offering compatibility with multi-dimensional tensors.

### How are the changes tested?

- Added unit tests:
  - 4 tests against trivial examples.
  - 1 test with common 8 students set.
  - 1 test testing for singularity.

## Checklist for Contributors

- [ ] Scope: This PR tackles exactly one problem.
- [ ] Conventions: The branch follows the `feature/title-slug` convention.
- [ ] Conventions: The PR title follows the `Bugfix: Title` convention.
- [ ] Coding style: The code passes all pre-commit hooks.
- [ ] Documentation: All changes are well-documented.
- [ ] Tests: New features are tested and all tests pass successfully.
- [ ] Changelog: Updated CHANGELOG.md for new features or breaking changes.
- [ ] Review: A suitable reviewer has been assigned.

## Checklist for Reviewers:

- [ ] The PR solves the issue it claims to solve and only this one.
- [ ] Changes are tested sufficiently and all tests pass.
- [ ] Documentation is complete and well-written.
- [ ] Changelog has been updated, if necessary.

2024-02-22 14:43 UTC, JakobEliasWagner commented on src/continuity/transforms/__init__.py
> +Standardization = ZNormalization
Renamed it to Normalize

2024-02-23 07:33 UTC, samuelburbulla requested changes
Better, but I still found some minor issues.

2024-02-23 07:33 UTC, samuelburbulla commented on src/continuity/transforms/scaling.py
> +        mean: mean value of the tensor.
Remove "of the tensor"

2024-02-23 07:33 UTC, samuelburbulla commented on src/continuity/transforms/scaling.py
> +        std: standard deviation of the tensor.
Remove "of the tensor"

2024-02-23 07:33 UTC, samuelburbulla commented on src/continuity/transforms/scaling.py
> +            std: standard deviation used to scale tensors in forward. Should have the same shape as the mean.
Hm, docstring says "Should have the same shape", but shape is checked (=enforced) by the assertion in line 33. I think we should let the freedom to have different shapes, e.g., a channel-wise mean but a scalar std or so. Remove assertion and comment in docstring.

2024-02-23 07:33 UTC, samuelburbulla commented on src/continuity/transforms/scaling.py
> +        if torch.allclose(std, torch.zeros(std.shape)):
We already introduced eps to prevent division by zero, why then throw a warning? It's similar to what we discussed in the transform, I assume the users nows what he is doing here, we shouldn't have to take care of misuse. Remove warning.

2024-02-23 07:33 UTC, samuelburbulla commented on src/continuity/transforms/scaling.py
> +    def backward(self, tensor: torch.Tensor) -> torch.Tensor:
docstring?

2024-02-23 09:58 UTC, JakobEliasWagner commented on src/continuity/transforms/scaling.py
> +    def backward(self, tensor: torch.Tensor) -> torch.Tensor:
Plus the method name followed the old structure.

2024-02-23 10:07 UTC, JakobEliasWagner commented on src/continuity/transforms/scaling.py
> +        if torch.allclose(std, torch.zeros(std.shape)):
Numerical stability with eps is only ensured when all values of the standard deviation are actually bigger than or equal to zero. This may lead to division by zero.

2024-02-23 10:12 UTC, JakobEliasWagner commented on src/continuity/transforms/scaling.py
> +        if torch.allclose(std, torch.zeros(std.shape)):
Thus my suggestion would be to adjust the method in the following way:

- Remove eps entirely
- Replace zero values in std with eps

This would enable negative std and ensure no `inf` value is introduced as an input.

2024-02-23 10:39 UTC, JakobEliasWagner commented
The reason as to why this test fails is unrelated to eps. Removed the comment in 
![image](https://github.com/aai-institute/continuity/assets/42122260/115b9bcf-ad1d-491f-9903-6d45aab18ac1)

2024-02-23 11:17 UTC, JakobEliasWagner commented
The previous plot is related to the range of the scaled tensor. The tests are performed for a range in the order of one -> 1e-7 is appropriate for testing.
![image](https://github.com/aai-institute/continuity/assets/42122260/31461266-d76e-4905-a858-7a5f865fd4d9)

2024-02-23 12:40 UTC, samuelburbulla commented
I improved the docs a little and set the random seed, because tests failed from time to time.

2024-02-23 12:43 UTC, merged