Bugfix/60 problem with kernel integral architecture
aai-institute/continuity pull request #63
Opened 2024-02-26 13:21 UTC by MLuchmann

# Bugfix: Problem with kernel integral architecture

## Description

The current implementation of the Integral Kernel layer only manages to learn the target function when the target space is discretized by only one value (shape(y) == (batch-size, 1, y-dim)) as it is the case in examples/selfsupervised.ipynb. However, when the target space is discretized with a value larger than 1, the operator fails to learn the target function (at least for specific examples).

### Which issue does this PR tackle?

  - New implementation of Neural Network Kernel is more general and fixes the issue.

### How does it solve the problem?

  - The Neural Network Kernel of the previous implementation was constructed as:
  $k(x_i, y_j) = NN\left( (x_i - y_j)^2 \right)$.
  The issue described above was due to the symmetric properties of the example combined with the specific construction of the kernel. The input function in basics.ipnyb has the property $u(-x) = -u(x)$. One can show that this property combined with the construction of our kernel leads to:
  $v_{pred}(y_j) = \frac{1}{N} \sum_i k(x_i, y_j) u(x_i) = -v_{pred}(-y_j)$. Therefore, the operator could only properly learn mappings from asym. to asym. functions (or sym. to sym.). 
  - The new kernel implementation is more general and does not rely on a convolution ($x_i - y_i$).
  
### Note

I had to change one of the test cases because I changed the way the IntegralKernel method processes the inputs x and y. Previously extra dimensions were added via ```.squeeze()```. I deleted these lines. The idea is that the reshaping is the responsibillity of the given kernel and not the IntegralKernel operation.

### How are the changes tested?

  - Tested via tests/test_neuraloperator.py
  - Tested via tests/test_convolution.py

## Checklist for Contributors

- [x] Scope: This PR tackles exactly one problem.
- [ ] Conventions: The branch follows the `feature/title-slug` convention.
- [ ] Conventions: The PR title follows the `Bugfix: Title` convention.
- [x] Coding style: The code passes all pre-commit hooks.
- [x] Documentation: All changes are well-documented.
- [x] Tests: New features are tested and all tests pass successfully.
- [x] Changelog: Updated CHANGELOG.md for new features or breaking changes.
- [x] Review: A suitable reviewer has been assigned.

## Checklist for Reviewers:

- [x] The PR solves the issue it claims to solve and only this one.
- [x] Changes are tested sufficiently and all tests pass.
- [x] Documentation is complete and well-written.
- [x] Changelog has been updated, if necessary.

2024-02-27 16:30 UTC, samuelburbulla requested changes
Looks good so far, but I think we have to outline the general concepts more clearly first.

What exactly is a `Kernel`? What is input/output of a kernel? 

Let's define an abstract base class first: I implemented the `Kernel` base class, I think this is what a kernel is. 
NeuralNetworkKernel should implement this signature (using an NN) and everything related to batching should be handled by the integral kernel. How does this sound to you?

We should do the same for the IntegralKernel, first defining a base class.

2024-02-27 16:30 UTC, samuelburbulla commented on src/continuity/operators/common.py
>  class NeuralNetworkKernel(torch.nn.Module):
We should move the `NeuralNetworkKernel` to `integralkernel.py`.

2024-02-27 16:30 UTC, samuelburbulla commented on src/continuity/operators/neuraloperator.py
> +            NeuralNetworkKernel(shapes, kernel_width, kernel_depth),
I agree that we should pass the `shapes` to the kernel.

2024-02-27 16:30 UTC, samuelburbulla commented on src/continuity/operators/common.py
> +        self.input_shape = shapes.y.dim + shapes.x.num * shapes.x.dim
The kernel should not depend on `x.num`.

2024-02-27 16:30 UTC, samuelburbulla commented on src/continuity/operators/common.py
> +            shapes.x.num,
A kernel should output a matrix `R^{d_u \times d_v}`, independent of `x.num`.

2024-02-27 16:30 UTC, samuelburbulla commented on src/continuity/operators/common.py
> +        batch_size = x.shape[0]
This batching should be part of the `IntegralKernel`, the kernel itself is independent of the number of xs or ys passed. See my abstract base class implementation for the target signature of a `Kernel`, and this `NeuralNetworkKernel` should follow this concept. Everything else moves to the `(Naive)IntegralKernel`. Maybe we should also add an abstract base class for an `IntegralKernel`?

2024-02-27 16:30 UTC, samuelburbulla commented on src/continuity/operators/integralkernel.py
> +class Kernel(torch.nn.Module, ABC):
This is the general concept of a kernel. NeuralNetworkKernel should implement this using a neural network.

2024-02-28 08:16 UTC, samuelburbulla commented on src/continuity/operators/integralkernel.py
> +class Kernel(torch.nn.Module, ABC):
Actually, maybe it makes sense to use batched inputs (num_x, x_dim), (num_y, y_dim) for more efficient implementation?

2024-02-29 13:49 UTC, MLuchmann commented on src/continuity/operators/common.py
> +        x = self.act(x)
I added the suggested changes and opened another PR.

2024-02-29 13:51 UTC, MLuchmann commented on src/continuity/operators/common.py
>  class NeuralNetworkKernel(torch.nn.Module):
Good pont. Done.

2024-02-29 13:56 UTC, MLuchmann commented on src/continuity/operators/common.py
> +    """General Neural network kernel. The neural network is constructed as a simple
The doc string is updated now.

2024-02-29 14:00 UTC, MLuchmann commented on src/continuity/operators/common.py
> +        self.input_shape = shapes.y.dim + shapes.x.num * shapes.x.dim
The kernel got reimplemented and does not depend on x.num any longer.

2024-02-29 17:32 UTC, samuelburbulla commented on src/continuity/operators/integralkernel.py
> +        # https://stackoverflow.com/questions/72782751/how-to-perform-torch-meshgrid-over-multiple-tensors-in-parallel
What does it mean "only works for 1d function"? x.dim == y.dim == 1?

2024-03-01 08:32 UTC, MLuchmann commented on src/continuity/operators/integralkernel.py
> +        # https://stackoverflow.com/questions/72782751/how-to-perform-torch-meshgrid-over-multiple-tensors-in-parallel
Sorry, the comment is misleading. I will delete the text in the brackets. I believe torch.meshgrid could have been used to create all combinations of $x_i$ and $y_j$, even though we do not necessary have a grid because $x$ and $y$ can be given at any position. However, we can't use it because the function only allows 1d tensors.

2024-03-01 10:55 UTC, samuelburbulla commented on src/continuity/operators/integralkernel.py
> +        # https://stackoverflow.com/questions/72782751/how-to-perform-torch-meshgrid-over-multiple-tensors-in-parallel
I added a test for the NeuralNetworkKernel (because I was not sure if this was working for several dimensions) and it turned out I had to change the code a little bit. Now it works and is tested :)

2024-03-01 11:03 UTC, samuelburbulla approved these changes

2024-03-01 11:49 UTC, merged