Feature: Regular Grid Sampler
aai-institute/continuity pull request #64
Opened 2024-02-26 15:40 UTC by JakobEliasWagner

# Feature: Regular Grid Sampler

## Description

This pull request introduces a new `RegularGridSampler` class, enhancing the sampling capabilities within n-dimensional hyperrectangles. The sampler is designed to generate samples that are as uniformly distributed across the grid as possible, with added functionality to handle over and undersampling when the requested number of samples cannot be perfectly achieved.

### Which issue does this PR tackle?

  - Regular grids currently need to be sampled manually.
  - For more general descriptions of functions, function-spaces and their discrete representations a multitude of different samplers and sampling strategies are required.

### How does it solve the problem?

  - Uniform Sampling: Efficiently samples from n-dimensional hyperrectangles to ensure a uniform distribution.
  - Flexible Sampling Options: Supports both oversampling and undersampling to facilitate sampling if the exact number of requested samples can not be achieved.

### How are the changes tested?

  - Added unit-tests to ensure functionality.

## Checklist for Contributors

- [ ] Scope: This PR tackles exactly one problem.
- [ ] Conventions: The branch follows the `feature/title-slug` convention.
- [ ] Conventions: The PR title follows the `Bugfix: Title` convention.
- [ ] Coding style: The code passes all pre-commit hooks.
- [ ] Documentation: All changes are well-documented.
- [ ] Tests: New features are tested and all tests pass successfully.
- [ ] Changelog: Updated CHANGELOG.md for new features or breaking changes.
- [ ] Review: A suitable reviewer has been assigned.

## Checklist for Reviewers:

- [ ] The PR solves the issue it claims to solve and only this one.
- [ ] Changes are tested sufficiently and all tests pass.
- [ ] Documentation is complete and well-written.
- [ ] Changelog has been updated, if necessary.

2024-02-26 15:41 UTC, JakobEliasWagner commented
Currently the target branch is still `feature/sampler` as this feature is dependent on the features of this branch.

2024-02-28 09:02 UTC, samuelburbulla requested changes
Looks good! Just make the rule how the grid is computed more concise in the class' docstring (preferably in formulas).

2024-02-28 09:02 UTC, samuelburbulla commented on src/continuity/discrete/regular_grid.py
> +        """Adjust the samples distribution to better fit the total_samples requirement.
Looks good, too, but please explain in the docstring.

2024-02-28 09:07 UTC, samuelburbulla commented
Please update the CHANGELOG as `RegularGridSampler` is a new feature.

2024-02-28 13:20 UTC, JakobEliasWagner commented on src/continuity/discrete/regular_grid.py
> +        self.x_aspect = self.x_delta / torch.sum(self.x_delta)
Added a test and changed the implementation to account for that.

2024-02-28 14:39 UTC, merged